### ISSUE TITLE
cape复现问题

### ISSUE THREAD

**Issue by zhuang999** [dsj96/PPR-master#1]
你好同学，Content-Aware Hierarchical Point-of-Interest Embedding Model for Successive POI Recommendation这篇论文你也有复现吗？可以讨论一下呀（我的微信：18525373238）

**Comment by dsj96** [comment]
这篇论文是有官方复现的```https://github.com/qnfnwkd/CAPE```，不过需要自己处理其中的Embedding

**Comment by zhuang999** [comment]
> 这篇论文是有官方复现的```https://github.com/qnfnwkd/CAPE```，不过需要自己处理其中的Embedding
> 
> 

是的，我已经复现这篇论文但是结果比论文里的数据高0.1，所以想和你讨论一下。

**Comment by wei0699** [comment]
同学你好，我想请问一下，代码里的vec_2nd_wo_norm.txt是怎么得到的呢？
