### ISSUE TITLE
对于输入数据的疑问

### ISSUE THREAD

**Issue by wei0699** [dsj96/PPR-master#2]
同学你好，我想请问一下，代码里的vec_2nd_wo_norm.txt是怎么得到的呢？

**Comment by dsj96** [comment]
通过构建user-poi图作为输入，再通过```line.cpp```文件得到嵌入（一阶，二阶），，具体可参考[LINE](https://github.com/tangjianpku/LINE),希望对你有些帮助

**Comment by wei0699** [comment]
> 通过构建user-poi图作为输入，再通过`line.cpp`文件得到嵌入（一阶，二阶），，具体可参考[LINE](https://github.com/tangjianpku/LINE),希望对你有些帮助

感谢您的回复，对我的帮助很大！
